version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: on-failure
    logging:
      driver: none

  redis:
    image: redis:4.0.14-alpine
    volumes:
      - redis:/data:delegated
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    restart: on-failure
    logging:
      driver: none

  app:
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3000" # Use port 3001 on the host instead of 3000
    environment:
      REDIS_URL: "redis://redis:${REDIS_PORT}/0"
      RAILS_ENV: "development"
      SECRET_KEY_BASE: "dummy_secret_key" # Replace with actual secret in production
      DATABASE_URL: postgres://postgres:postgres@postgres/action_pdf_development
      GROVER_NO_SANDBOX: true
    volumes:
      - .:/rails:delegated
    # command: ./bin/rails server -b 0.0.0.
    stdin_open: true # Keeps stdin open
    tty: true # Allows an interactive terminal
volumes:
  postgresql:
  redis:
networks:
  backend:
    driver: "bridge"
