default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgresql
  host: <%= ENV.fetch("DATABASE_HOST", "postgres") %>
  port: <%= ENV.fetch("DATABASE_PORT", "5432") %>

development:
  <<: *default
  database: action_pdf_development
  username: postgres
  password: postgres
  port: 5432

test:
  <<: *default
  database: action_pdf_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: action_pdf_production
  username: postgres
  password: postgres
